language: ruby

addons:
  postgresql: "9.6"

services:
  - postgresql
  - memcached
  - redis-server
  - elasticsearch

cache:
  bundler: true

rvm:
  - 2.6.2

matrix:
  fast_finish: true

before_install:
  - psql -c "CREATE USER \"admin\" WITH CREATEDB PASSWORD 'admin';" -U postgres
  - psql -c "create database \"bluedoc-test\" WITH OWNER=\"admin\";" -U postgres

install:
  - bundle --quiet --jobs 3
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate

script:
  - RAILS_ENV=test bundle exec rake
  - bundle exec rubocop .
