version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
      - image: node:11-alpine
      - image: circleci/postgres:9.6
      - image: circleci/redis:4-alpine3.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            yarn

      - save_cache:
          paths:
            - ./vendor/bundle
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: bundle exec rake test