# config/app.yml for rails-settings-cached
defaults: &defaults
  host: '<%= ENV['APP_HOST'] || "http://localhost:3000" %>'
  mailer_from: <%= ENV["MAILER_FROM"] || "no-reply@booklab.io" %>
  mailer_options:
    address: '<%= ENV['SMTP_ADDRESS'] %>'
    port: <%= ENV['SMTP_PORT'] || 25 %>
    domain: '<%= ENV['SMTP_DOMAIN'] %>'
    user_name: '<%= ENV['SMTP_USERNAME'] %>'
    password: '<%= ENV['SMTP_PASSWORD'] %>'
    authentication: '<%= ENV['SMTP_AUTHENTICATION'] || "login" %>'
    enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] || true %>
  plantuml_service_host: <%= ENV['PLANTUML_SERVICE_HOST'] || 'http://localhost:1608' %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
