# config/app.yml for rails-settings-cached
defaults: &defaults
  host: '<%= ENV['APP_HOST'] || "http://localhost:3000" %>'
  mailer_from: <%= ENV["MAILER_FROM"] || "no-reply@bluedoc.io" %>
  mailer_delivery_method: '<%= ENV["MAILER_DELIVERY_METHOD"] || "sendmail" %>'
  mailer_options:
    address: '<%= ENV['SMTP_ADDRESS'] %>'
    port: <%= ENV['SMTP_PORT'] || 25 %>
    domain: '<%= ENV['SMTP_DOMAIN'] %>'
    user_name: '<%= ENV['SMTP_USERNAME'] %>'
    password: '<%= ENV['SMTP_PASSWORD'] %>'
    authentication: '<%= ENV['SMTP_AUTHENTICATION'] || "login" %>'
    enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] || true %>
  ldap_enable: "<%= ENV["LDAP_ENABLE"] || "0" %>"
  ldap_options:
    title: "<%= ENV["LDAP_TITLE"] || "LDAP Login" %>"
    host: "<%= ENV["LDAP_HOST"] || "localhost" %>"
    # LDAP server. `:plain` means no encryption. `:simple_tls` represents SSL/TLS
    # (usually on port 636) while `:start_tls` represents StartTLS (usually port 389).
    encryption: "<%= ENV["LDAP_ENCRYPTION"] || "plain" %>"
    port: "<%= ENV["LDAP_HOST"] || "389" %>"
    base: "<%= ENV["LDAP_BASE"] || "dc=example,dc=org" %>"
    # Typically AD would be 'sAMAccountName' or 'UserPrincipalName', while OpenLDAP is 'uid'.
    uid: "<%= ENV["LDAP_UID"] || "uid" %>"
    # Most LDAP servers require that you supply a complete DN as a binding-credential, along with an authenticator
    # such as a password. But for many applications, you often don’t have a full DN to identify the user.
    # You usually get a simple identifier like a username or an email address, along with a password.
    #
    # - bind_dn - the admin username
    # - password - the admin password
    bind_dn: "<%= ENV["LDAP_BIND_DN"] || "cn=admin,dc=example,dc=org" %>"
    password: "<%= ENV["LDAP_PASSWORD"] || "admin" %>"

development:
  <<: *defaults

test:
  <<: *defaults
  # Set Setting.host same as Rails integration test default host
  host: 'http://www.example.com'

production:
  <<: *defaults
