default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 64 } %>

development:
  <<: *default
  database: bluedoc-dev

test:
  <<: *default
  database: bluedoc-test

production:
  <<: *default
  database: bluedoc-prod
  username: bluedoc
  password: <%= ENV['BOOKLAB_DATABASE_PASSWORD'] %>
