default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: booklab_development

test:
  <<: *default
  database: booklab_test

production:
  <<: *default
  database: booklab_production
  username: booklab
  password: <%= ENV['BOOKLAB_DATABASE_PASSWORD'] %>
