user:
  - new
  - doc
  - docs
  - repository
  - repositories
  - group
  - groups
  - account
  - accounts
  - user
  - users
  - dashboard
  - dashboards
  - help
  - login
  - slug
  - setting
  - settings
  - star
  - stars
  - watch
  - watches
  - like
  - action
  - import
  - search
  - autocomplete
  - upload
  - uploads
  - admins
  - version
  - versions
  - share
  - shares
  - comments
  - comment