---
:concurrency: <%= ENV["sidekiq_threads"] || 20 %>
:logfile: log/sidekiq.log
:queues:
  - [bluedoc_default, 10]
  - [default, 10]
  - [bluedoc_mailers, 5]
  - [mailers, 5]
  - [bluedoc_index, 3]
  - [index, 3]
