---
:concurrency: <%= ENV["SIDEKIQ_MAX_THREADS"] || 32 %>
:logfile: log/sidekiq.log
:queues:
  - [default, 10]
  - [mailers, 5]
  - [bluedoc_default, 10]
  - [bluedoc_mailers, 5]
  - [bluedoc_active_storage_analysis, 5]
  - [bluedoc_index, 3]

