test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] || "need-access-key-id" %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] || "need-secret-access-key" %>
  region: <%= ENV["AWS_S3_REGION"] || "us-east-1" %>
  bucket: <%= ENV["AWS_S3_BUCKET"] || "booklab" %>

aliyun:
  service: Aliyun
  access_key_id: <%= ENV["ALIYUN_ACCESS_KEY_ID"]  || "need-access-key-id" %>
  access_key_secret: <%= ENV["ALIYUN_ACCESS_KEY_SECRET"]  || "need-access-key-secret" %>
  bucket: <%= ENV["ALIYUN_BUCKET"] || "booklab" %>
  endpoint: <%= ENV["ALIYUN_ENDPOINT"] || "https://oss-cn-beijing.aliyuncs.com" %>
  mode: <%= ENV["ALIYUN_MODE"] || "private" %>
  cname: <%= ENV["cname"] || false %>


# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
