name: Test

on: [push]
jobs:
  lint:
    name: AutoCorrect Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: huacnlee.autocorrect
        uses: huacnlee/autocorrect-action@0.0.3
  test:
    name: CI Test
    runs-on: ubuntu-latest
    container: bluedoc/base:2.7.2-alpine
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: bluedoc-test
          POSTGRES_USER: "admin"
          POSTGRES_PASSWORD: "123456"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgres://admin:123456@postgres:5432/bluedoc-test
      LDAP_HOST: localhost
      OMNIAUTH_GOOGLE_CLIENT_ID: fake-client-id
      OMNIAUTH_GOOGLE_CLIENT_SECRET: fake-client-secret
    steps:
      - uses: actions/checkout@v2
      - name: RubyGems cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Before tests
        run: |
          sed -i "s/gems.ruby-china.org/rubygems.org/g" Gemfile.lock
          bundle exec rails db:migrate
      - name: Run Lints
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rails test
